"""empty message

Revision ID: 096057bb3435
Revises: 2daaf569f64d
Create Date: 2021-09-19 01:29:38.703707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096057bb3435'
down_revision = '2daaf569f64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Auth0user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('picture'),
    sa.UniqueConstraint('username')
    )
    op.add_column('Mygame', sa.Column('owner', sa.String(), nullable=False))
    op.create_foreign_key(None, 'Mygame', 'Auth0user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Mygame', type_='foreignkey')
    op.drop_column('Mygame', 'owner')
    op.drop_table('Auth0user')
    # ### end Alembic commands ###
