"""empty message

Revision ID: 26561c5f9ad7
Revises: 9a06232cd760
Create Date: 2021-09-21 21:50:16.326493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26561c5f9ad7'
down_revision = '9a06232cd760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Game_name_key', 'Game', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Game_name_key', 'Game', ['name'])
    # ### end Alembic commands ###
