"""initialize database

Revision ID: 2daaf569f64d
Revises: 
Create Date: 2021-09-19 00:00:09.132368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2daaf569f64d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('platform', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('genre', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cover_link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('distributor', sa.String(length=150), nullable=False),
    sa.Column('publisher', sa.String(length=150), nullable=False),
    sa.Column('developer', sa.String(length=150), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Mygame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('play_status', sa.Boolean(), nullable=True),
    sa.Column('purchased_on', sa.DateTime(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game'], ['Game.id'], ),
    sa.ForeignKeyConstraint(['vendor'], ['Vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Mygame')
    op.drop_table('Vendor')
    op.drop_table('Game')
    # ### end Alembic commands ###
