"""empty message

Revision ID: 2e8242117e00
Revises: 97004b509ede
Create Date: 2021-09-21 19:40:38.171182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8242117e00'
down_revision = '97004b509ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Mygame_game_key', 'Mygame', type_='unique')
    op.drop_constraint('Mygame_vendor_key', 'Mygame', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Mygame_vendor_key', 'Mygame', ['vendor'])
    op.create_unique_constraint('Mygame_game_key', 'Mygame', ['game'])
    # ### end Alembic commands ###
