"""empty message

Revision ID: 37c5a1dbff55
Revises: e3a2994dd76f
Create Date: 2021-09-21 20:38:58.971222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37c5a1dbff55'
down_revision = 'e3a2994dd76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Vendor', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('Vendor', 'distributor',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('Vendor', 'publisher',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('Vendor', 'developer',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('Vendor', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Vendor', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('Vendor', 'developer',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('Vendor', 'publisher',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('Vendor', 'distributor',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('Vendor', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
