"""empty message

Revision ID: 6ff6b2ed8ebb
Revises: 1ac0b59a7c89
Create Date: 2021-09-21 22:38:17.131009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff6b2ed8ebb'
down_revision = '1ac0b59a7c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Game_name_key', 'Game', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Game_name_key', 'Game', ['name'])
    # ### end Alembic commands ###
