"""empty message

Revision ID: 7206f7381663
Revises: 096057bb3435
Create Date: 2021-09-19 01:37:17.070169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7206f7381663'
down_revision = '096057bb3435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Game', sa.Column('vendor', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Game', 'Vendor', ['vendor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Game', type_='foreignkey')
    op.drop_column('Game', 'vendor')
    # ### end Alembic commands ###
