"""empty message

Revision ID: 7bbc6b225975
Revises: 6ff6b2ed8ebb
Create Date: 2021-09-24 06:08:30.920840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbc6b225975'
down_revision = '6ff6b2ed8ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Auth0user', sa.Column('role', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Auth0user', 'role')
    # ### end Alembic commands ###
