"""empty message

Revision ID: 97004b509ede
Revises: d2322b55af28
Create Date: 2021-09-21 01:39:14.743106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97004b509ede'
down_revision = 'd2322b55af28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Mygame', ['vendor'])
    op.create_unique_constraint(None, 'Mygame', ['game'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Mygame', type_='unique')
    op.drop_constraint(None, 'Mygame', type_='unique')
    # ### end Alembic commands ###
