"""empty message

Revision ID: 9a06232cd760
Revises: 37c5a1dbff55
Create Date: 2021-09-21 21:04:00.187032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a06232cd760'
down_revision = '37c5a1dbff55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Vendor_release_date_key', 'Vendor', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Vendor_release_date_key', 'Vendor', ['release_date'])
    # ### end Alembic commands ###
