"""empty message

Revision ID: d2322b55af28
Revises: 7206f7381663
Create Date: 2021-09-20 21:33:57.008310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2322b55af28'
down_revision = '7206f7381663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sysAuth0TokenStorage',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysAuth0TokenStorage')
    # ### end Alembic commands ###
