"""empty message

Revision ID: e3a2994dd76f
Revises: 2e8242117e00
Create Date: 2021-09-21 20:38:22.307218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3a2994dd76f'
down_revision = '2e8242117e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Vendor', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('Vendor', 'distributor',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('Vendor', 'publisher',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('Vendor', 'developer',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('Vendor', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'Vendor', ['release_date'])
    op.create_unique_constraint(None, 'Vendor', ['developer'])
    op.create_unique_constraint(None, 'Vendor', ['name'])
    op.create_unique_constraint(None, 'Vendor', ['publisher'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Vendor', type_='unique')
    op.drop_constraint(None, 'Vendor', type_='unique')
    op.drop_constraint(None, 'Vendor', type_='unique')
    op.drop_constraint(None, 'Vendor', type_='unique')
    op.alter_column('Vendor', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('Vendor', 'developer',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('Vendor', 'publisher',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('Vendor', 'distributor',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('Vendor', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
